//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Policlinica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnoz
    {
        public Diagnoz()
        {
            this.Lechenie = new HashSet<Lechenie>();
        }
    
        public int Id { get; set; }
        public string Диагноз { get; set; }
        public string Описание { get; set; }
    
        public virtual ICollection<Lechenie> Lechenie { get; set; }
    }
}
