//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Policlinica.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Lechenie
    {
        public int Id { get; set; }
        [Required]
        public string Рецепт { get; set; }
        [Required]
        public Nullable<int> Диагноз { get; set; }
        public Nullable<int> Время { get; set; }
        public Nullable<int> Врач { get; set; }
        public Nullable<int> Пациент { get; set; }
    
        public virtual Diagnoz Diagnoz { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual Vrem Vrem { get; set; }
        public virtual UserProfile UserProfile1 { get; set; }
    }
}
