//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Policlinica.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class Otdelenie
    {
        public Otdelenie()
        {
            this.UserProfile = new HashSet<UserProfile>();
        }
    
        public int Id { get; set; }
        [Required]
        [Display(Name = "Отделение")]
        public string Название_отделени { get; set; }
    
        public virtual ICollection<UserProfile> UserProfile { get; set; }
    }
}
