//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Policlinica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uvedomlenie
    {
        public int Id { get; set; }
        public string Текст { get; set; }
        public Nullable<int> Получатель { get; set; }
        public string Статус { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
