//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Policlinica.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class Vrem
    {
        public Vrem()
        {
            this.Lechenie = new HashSet<Lechenie>();
        }
    
        public int Id { get; set; }
        public Nullable<System.TimeSpan> Время { get; set; }
        public Nullable<int> Врач { get; set; }
        public string Статус { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd'.'MM'.'yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> Дата { get; set; }
        public Nullable<int> Пациент { get; set; }
    
        public virtual ICollection<Lechenie> Lechenie { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual UserProfile UserProfile1 { get; set; }
    }
}
